name: Terraform Pipelibe

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  TF_VERSION: 1.5.7  # Updated to latest version

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Clean Terraform Cache
      run: rm -rf .terraform* terraform.tfstate*

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your region

    - name: Terraform Init
      run: terraform init -reconfigure

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan
      
    - name: Deploy to Production
 #    if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
